spring.application.name=spring-learn
server.port=8083

# Logging Configurations
logging.level.root=INFO
logging.level.com.cognizant.springlearn=DEBUG
logging.level.com.cognizant.spring_learn=DEBUG

# Custom Logging Pattern
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
